TestBlog/Controllers/AdminController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TestBlog.Data;
using TestBlog.Models;
using TestBlog.Models.CoinMarketCap;
using TestBlog.ViewModels;

namespace TestBlog.Controllers
{
    public class AdminController : Controller
    {
        private readonly UserManager<myIdentityUser> _userManager;
        private readonly SignInManager<myIdentityUser> _signInManager;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IBlogRepo _blogRepository;

        public AdminController(UserManager<myIdentityUser> userManager, SignInManager<myIdentityUser> signInManager,
            IHostingEnvironment hostingEnvironment, IBlogRepo blogRepository)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            this.hostingEnvironment = hostingEnvironment;
            this._blogRepository = blogRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AdminSignUP()
        {
            ViewBag.FormTitle = "Admin SignUp Page";
            var Post = GetAllpost();
            var typcount = _blogRepository.TypeCount();
            ViewBag.Allpost = (IEnumerable<RePost>)Post;
            ViewBag.CatigoryTypeCount = typcount;
            // loading coins to layout
            var Crypto = await returnCoinToLayout();
            ViewBag.Crypto = Crypto;
            return View();
        
        }
  
        public async Task<IEnumerable<CryptoMarketResponse>> returnCoinToLayout()
        {
            CoinProcessor processorR = new CoinProcessor();
            var coinAndPrices = await processorR.LoadCoins();
            var Crypto = (IEnumerable<CryptoMarketResponse>)coinAndPrices;
            return Crypto;
        }

        [HttpPost]
        public async Task<IActionResult> AdminSignUP(AdminViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (model.Photo != null)
                {
                   
                    string upload = hostingEnvironment.ContentRootPath;
                    var uploadsFolder = Path.Combine(upload, "wwwroot/images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                // Copy data from RegisterViewModel to IdentityUser
                var user = new myIdentityUser
                {
                    Photophath = uniqueFileName,
                    Fullname = (model.LastName.Trim() + " " + model.FirstName.Trim()),
                    UserName = model.UserName.Trim(),
                    Email = model.Email.Trim(),
                    GetUserType= UserType.Admin,
                    customid= model.LastName.Trim()+"-"+model.FirstName.Trim()+"_"
                };

                // Store user data in AspNetUsers database table
                var result = await _userManager.CreateAsync(user, model.Password.Trim());
                
                //  If user is successfully created, sign-in the user using
                // SignInManager and redirect to index action of HomeController
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    var Post = GetAllpost();
                    var typcount = _blogRepository.TypeCount();
                    ViewBag.Allpost = (IEnumerable<RePost>)Post;
                    ViewBag.CatigoryTypeCount = typcount;
                    // loading coins to layout
                    var Crypto = await returnCoinToLayout();
                    ViewBag.Crypto = Crypto;
                    return RedirectToAction("index", "home");
                }

                // If there are any errors, add them to the ModelState object
                // which will be displayed by the validation summary tag helper
                else
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

            }
             
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AdminLogIn()
        {
            ViewBag.FormTitle = "Admin Login Page";
            var Post = GetAllpost();
            var typcount = _blogRepository.TypeCount();
            ViewBag.Allpost = (IEnumerable<RePost>)Post;
            ViewBag.CatigoryTypeCount = typcount;
            // loading coins to layout
            var Crypto = await returnCoinToLayout();
            ViewBag.Crypto = Crypto;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AdminLogIn(LogInViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _signInManager.PasswordSignInAsync(
                        model.Email.Trim(), model.Password.Trim(), model.RemenberMe, false);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("index", "home");
                    }
                    else { 
                    var Post = GetAllpost();
                    var typcount = _blogRepository.TypeCount();
                    ViewBag.Allpost = (IEnumerable<RePost>)Post;
                    ViewBag.CatigoryTypeCount = typcount;
                    // loading coins to layout
                    var Crypto = await returnCoinToLayout();
                    ViewBag.Crypto = Crypto;
                    ModelState.AddModelError(string.Empty, "Invalid Login Attempt");
                    }
                }

                return View(model);
            }
            catch (Exception e)
            {

                return null;
            }
        
        }

        public async Task<IActionResult> LogOutAdmin()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public IEnumerable<RePost> GetAllpost()
        {
            List<RePost> rePosts = new List<RePost>();
            var NewsUpdate = _blogRepository.GetALLpost();
            foreach (var post in NewsUpdate)
            {
                var postToUse = new RePost();
                postToUse.Date = post.Date;
                postToUse.Discription = post.Discription;
                postToUse.Headline = post.Headline;
                postToUse.Photopath = post.Photopath;
                postToUse.PostId = post.PostId;
                postToUse.postWriteUp = post.postWriteUp;
                rePosts.Add(postToUse);
            }
            var OurPost = _blogRepository.addLikes(rePosts);
            var Post = _blogRepository.AddComents(OurPost);
            return Post;
        }
    }
}

TestBlog/Controllers/UserController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TestBlog.Data;
using TestBlog.Models;
using TestBlog.Models.CoinMarketCap;
using TestBlog.ViewModels;

namespace TestBlog.Controllers
{
    public class UserController:Controller
    {
        private readonly UserManager<myIdentityUser> _userManager;
        private readonly SignInManager<myIdentityUser> _signInManager;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IBlogRepo _blogRepository;

        public UserController(UserManager<myIdentityUser> userManager, SignInManager<myIdentityUser> signInManager, IHostingEnvironment
            hostingEnvironment, IBlogRepo blogRepository)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            this.hostingEnvironment = hostingEnvironment;
            this._blogRepository = blogRepository;
        }

        [HttpGet]
        public async Task<IActionResult> UserSignUP()
        {

            ViewBag.FormTitle = "User SignUp Page";
            var Post = GetAllpost();
            var typcount = _blogRepository.TypeCount();
            ViewBag.Allpost = (IEnumerable<RePost>)Post;
            ViewBag.CatigoryTypeCount = typcount;
            // loading coins to layout
            var Crypto = await returnCoinToLayout();
            ViewBag.Crypto = Crypto;
            return View("~/Views/Admin/AdminSignUP.cshtml");
        }
        public async Task<IEnumerable<CryptoMarketResponse>> returnCoinToLayout()
        {
            CoinProcessor processorR = new CoinProcessor();
            var coinAndPrices = await processorR.LoadCoins();
            var Crypto = (IEnumerable<CryptoMarketResponse>)coinAndPrices;
            return Crypto;
        }

        [HttpPost]
        public async Task<IActionResult> UserSignUP(AdminViewModel model)
        {

            
                string uniqueFileName = null;
                if (model.Photo != null)
                {

                    string upload = hostingEnvironment.ContentRootPath;
                    var uploadsFolder = Path.Combine(upload, "wwwroot/images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                // Copy data from RegisterViewModel to IdentityUser
                var user = new myIdentityUser
                {
                    Photophath = uniqueFileName,
                    Fullname = (model.LastName + " " + model.FirstName),
                    UserName = model.UserName,
                    Email = model.Email.Trim(),
                    GetUserType = UserType.User,
                    customid = model.LastName + "-" + model.FirstName + "_"
                }; 

                // Store user data in AspNetUsers database table
                var result = await _userManager.CreateAsync(user, model.Password.Trim());

                //  If user is successfully created, sign-in the user using
                // SignInManager and redirect to index action of HomeController
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                var Post = GetAllpost();
                var typcount = _blogRepository.TypeCount();
                ViewBag.Allpost = (IEnumerable<RePost>)Post;
                ViewBag.CatigoryTypeCount = typcount;
                // loading coins to layout
                var Crypto = await returnCoinToLayout();
                ViewBag.Crypto = Crypto;
                return RedirectToAction("index", "home");
                }

            // If there are any errors, add them to the ModelState object
            // which will be displayed by the validation summary tag helper
            else { 
                     foreach (var error in result.Errors)
                         {
                             ModelState.AddModelError(string.Empty, error.Description);
                          }
            }


            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> UserLogIn()
        {

            ViewBag.FormTitle = "User Login Page";
            var Post = GetAllpost();
            var typcount = _blogRepository.TypeCount();
            ViewBag.Allpost = (IEnumerable<RePost>)Post;
            ViewBag.CatigoryTypeCount = typcount;
            // loading coins to layout
            var Crypto = await returnCoinToLayout();
            ViewBag.Crypto = Crypto;
            return View("~/Views/Admin/AdminLogIn.cshtml");
        }
        [HttpPost]
        public async Task<IActionResult> UserLogIn(LogInViewModel model)
        {

                var result = await _signInManager.PasswordSignInAsync(
                    model.Email.Trim(), model.Password.Trim(), model.RemenberMe, false);

                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }
            else {      
                ModelState.AddModelError(string.Empty, "Invalid Login Attempt");
                 }

            return View("~/Views/Admin/AdminLogIn.cshtml", model);
        }

        public async Task<IActionResult> LogOutAdmin()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IEnumerable<RePost> GetAllpost()
        {
            List<RePost> rePosts = new List<RePost>();
            var NewsUpdate = _blogRepository.GetALLpost();
            foreach (var post in NewsUpdate)
            {
                var postToUse = new RePost();
                postToUse.Date = post.Date;
                postToUse.Discription = post.Discription;
                postToUse.Headline = post.Headline;
                postToUse.Photopath = post.Photopath;
                postToUse.PostId = post.PostId;
                postToUse.postWriteUp = post.postWriteUp;
                rePosts.Add(postToUse);
            }
            var OurPost = _blogRepository.addLikes(rePosts);
            var Post = _blogRepository.AddComents(OurPost);
            return Post;
        }
    }

}

TestBlog/Views/Shared/NotFound.cshtml
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<form class="card" Mt="20" mb="50">
    <p><h1 class="text-center">Not Found</h1></p>
    <div class="newsletter-input text-center">
        <h1>@ViewBag.ErrorMessage</h1>
    </div>
    <div class="blog-bottom text-center text-danger">
        <a asp-action="index" asp-controller="home">Click here to go back to Home-page</a>
    </div>
</form>

TestBlog/Views/Shared/_Layout2.cshtml
@inject SignInManager<TestBlog.Data.myIdentityUser > signINmanager;
@inject UserManager<TestBlog.Data.myIdentityUser> usermanager ;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers


<html class="no-js">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Blog's Name : Home of Infomation</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- xxx Favicons xxx -->
    <!-- xxx Base Stylesheet xxx -->
    <script src="js/modernizr-2.6.2.min.js"></script>

    <link rel="stylesheet" media="screen" href="/css/base.css" />
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />


</head>

<body>
    <body class="wide">

        <!-- xxx Loader Start xxx -->
        <div id="pageloader">
            <div class="loader-item">
                <img src="/images/preloader.gif" alt='loader' />
                <div>Loading...</div>
            </div>
        </div>
    </body>
    <!-- xxx End xxx -->
    <!-- xxx Header Start xxx -->
    <header>
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        A Bright Sunny Day Or Some Line Of Text
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons">
                            <ul>
                                <li><a href="#" data-toggle="tooltip" title="" data-original-title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" data-toggle="tooltip" title="" data-original-title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" data-toggle="tooltip" title="" data-original-title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#" data-toggle="tooltip" title="" data-original-title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                                <li>
                                    <div class="box-search">
                                        <input class="search-input" type="search" placeholder="Search" />
                                        <div class="icon"></div>
                                    </div>
                                    <a href="#" class="icon"><i class="fa fa-search"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="nav-wrap">
            <div class="container">
                <div id="menuzord" class="menuzord red pull-left">
                    <a href="javascript:void(0)" class="menuzord-brand"><img src="/images/logo.png" alt="Ruaha Logo"></a>
                    <ul class="menuzord-menu">
                        <li><a href="/">Home</a></li>
                        <li>
                            <a href="#">news</a>
                            <ul class="dropdown">
                                <li><a href="/home/GetPostByDiscription/2">Sports</a></li>
                                <li><a href="/home/GetPostByDiscription/1">Entertainment</a></li>
                                <li><a href="/home/GetPostByDiscription/3">Travels</a></li>
                                <li><a href="/home/GetPostByDiscription/4">LifeStyle</a></li>
                                <li><a href="/home/GetPostByDiscription/5">Jobs</a></li>
                                <li><a href="/home/GetPostByDiscription/6">Movies</a></li>
                                <li><a href="/home/GetPostByDiscription/7">Music</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Contact Us</a>
                            <ul class="dropdown">
                                <li><a href="">Egbule.goodluck@gmail</a></li>
                            </ul>
                        </li>


                        <li>
                            <a>
                                <div class="search-container">
                                    <form asp-controller="Home" asp-action="GetPostByHeadline" method="post">
                                        <input type="text" placeholder="Search" name="HeadLine" style="width:70px;">
                                        <button type="submit" style="width:30px;height:30px"><i class="fa fa-search"></i></button>
                                    </form>
                                </div>
                            </a>
                        </li>
                        @if (signINmanager.IsSignedIn(User))
                        {

                            <li>

                                @{
                                    var myUser = await usermanager.GetUserAsync(User);
                                }

                                <a class="admin-text">
                                    @{
                                        var photo = "/images/" + myUser.Photophath;
                                    }
                                    <p><img src="@photo" alt="" class="img-circle" style="height:40px;width:40px"></p>
                            <li><a>LOGOUT<a class="dropdown" asp-action="LogOutUser" asp-controller="User">@myUser.Fullname</a> </a></li>

                            </li>
                        }
                        @if (signINmanager.IsSignedIn(User))
                        {
                            var myUser = await usermanager.GetUserAsync(User);
                            if (myUser.GetUserType.Equals(1))
                            {
                                <li><a asp-action="Create" asp-controller="Home">Post News</a></li>
                            }

                        }

                        else
                        {
                            <li>
                                <a href="#">Admin</a>
                                <ul class="dropdown">
                                    <li><a asp-action="AdminLogIn" asp-controller="Admin">Login</a></li>
                                    <li><a asp-action="AdminSignUP" asp-controller="Admin">SignUp</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">Account</a>
                                <ul class="dropdown">
                                    <li><a asp-action="UserLogIn" asp-controller="User">Login</a></li>
                                    <li><a asp-action="UserSignUP" asp-controller="User">SignUp</a></li>
                                </ul>
                            </li>
                        }
                    </ul>



</div>
            </div>
        </div>

        <div class="clearfix"></div>

    </header>

    <!-- xxx Header End xxx -->


    <div class="col-sm-12"style="float:unset">
            <main role="main">
                @RenderBody()
            </main>
    </div>

    @if (IsSectionDefined("Scripts"))
    {
@RenderSection("Scripts", required: false)}
    <!-- xxx Footer End xxx -->
    <!-- xxx Back To Top xxx -->
    <div id="back-top">
        <a class="/img-circle" href="#top">
            <i class="fa fa-angle-up"></i>
        </a>
    </div>
   




    <!-- xxx End xxx -->
    <!-- xxx Footer xxx -->
    <!-- xxx Footer End xxx -->
    <!-- xxx Style Switcher (Only For Demo) xxx -->
    <!-- JQuery Plugins-->
    <script type="text/javascript" src="/js/jquery-min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type='text/javascript' src="/js/menuzord.js"></script>
    <script type="text/javascript" src="/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/js/owl.carousel.min.js"></script>
    <script type='text/javascript' src="/js/jflickrfeed.min.js"></script>
    <script type='text/javascript' src="/js/jquery.fancybox.js"></script>
    <script type='text/javascript' src="/js/jquery.validate.min.js"></script>
    <script type='text/javascript' src="/twitter/jquery.tweet.js"></script>

    <!-- JQuery Map Plugin -->

    <script type="text/javascript" src="/js/jquery.gmap.min.js"></script>

    <script type='text/javascript' src="/js/site-custom.js"></script>

</body>
</html>